global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:     
  - job_name: 'basketapi'
    static_configs:
      - targets: ['host.docker.internal:5001'] # hard-coded port matches launchSettings.json- job_name: 'weatherapp'      
  - job_name: 'catalogapi'
    static_configs:
      - targets: ['host.docker.internal:50001'] # hard-coded port matches launchSettings.json     
  - job_name: 'discountapi'
    static_configs:
      - targets: ['host.docker.internal:59266'] # hard-coded port matches launchSettings.json      
  - job_name: 'orderapi'
    static_configs:
      - targets: ['host.docker.internal:5299'] # hard-coded port matches launchSettings.json
  - job_name: 'testapi'
    static_configs:
      - targets: ['host.docker.internal:5097'] # hard-coded port matches launchSettings.json
